### ISSUE TITLE
Bulk merger applies to all repos in alphagov

### ISSUE THREAD

**Issue by heathd** [alphagov/bulk-merger#14]
We've seen PRs approved in GOV.UK Pay repos by people not in our team. It turns out that this was triggered by the bulk merger tool.

The bulk merger tool should only apply to repos with a specific `topic` applied (eg. `govuk`)

**Comment by issyl0** [comment]
GitHub's API [doesn't support `topic` filters in search](https://developer.github.com/v3/search/#search-issues-and-pull-requests). But it does support [searching for topics](https://developer.github.com/v3/search/#search-topics) as a preview. Maybe something to look into as an intermediary step: get all the repos with `topic:govuk` and then do the rest of the filtering?

I'll try to find some time to look into this in the coming days.
